class Config {
  // only socket
  var socketUrl = 'https://ott2.mobifone.ai/';
  var jwt_token =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdHRfdXNlcl9pZCI6ImJhMTEyNDQyLWE1YTUtNGNhMy1iMWVmLTMyODI4OGVjZWQ2NiIsInVzZXJuYW1lIjoidGhhbmgiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImNyZWF0ZV90aW1lIjoiMjAyMS0wOC0yM1QxODoxNTowOS45MDZaIiwicGhvbmVfbnVtYmVyIjoiMDk2OTg2NDI2OCIsImRpc3BsYXlfbmFtZSI6InRoYW5oIiwiZGV2aWNlX2luZm8iOiJ3ZWIiLCJjb21wYW55X25hbWUiOiJNb2JpRm9uZS1JVEMiLCJhcHBfbmFtZSI6IlRFU1QiLCJpYXQiOjE2MzkzNzkxMjQsImV4cCI6MTYzOTk4MzkyNH0.1D_Hg8h3r7VrqSFAlzglaBsMlcCYn9RQtF8kGdZCQj0';

  var EVENT_MISS = "EVENT_MISS";
  var EVENT_CANCEL = "EVENT_CANCEL";
  var EVENT_REJECT = "EVENT_REJECT";
  var EVENT_ACCEPT = "EVENT_ACCEPT";
  var EVENT_RINGING = "EVENT_RINGING";
  var EVENT_CALLING = "EVENT_CALLING";
  var EVENT_END = "EVENT_END";
}
